base:
  DOIAU: "YES"
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_STARTMEM_FROM_JEDIICE: "NO"
  DO_GOES: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  DO_NPOESS: "NO"
  DO_TRACKER: "YES"
  DO_GENESIS: "YES"
  DO_GENESIS_FSU: "NO"
  DO_METP: "YES"
  FHMAX_GFS: 120
  FHMAX_HF_GFS: 0
  FCST_BREAKPOINTS: ""
  GSI_SOILANAL: "NO"
  EUPD_CYC: "gdas"
  FHMAX_ENKF_GFS: 12
  DOHYBVAR_OCN: "NO"
  DO_TEST_MODE: "NO"

atmanl:
  JCB_ALGO_YAML_VAR: "${PARMgfs}/gdas/atm/jcb-prototype_3dvar.yaml.j2"
  JCB_ALGO_YAML_FV3INC: "${PARMgfs}/gdas/atm/jcb-prototype_3dvar-fv3inc.yaml.j2"
  STATICB_TYPE: "gsibec"
  LAYOUT_X_ATMANL: 8
  LAYOUT_Y_ATMANL: 8
  IO_LAYOUT_X: 1
  IO_LAYOUT_Y: 1

atmensanl:
  JCB_ALGO_YAML_LETKF: "${PARMgfs}/gdas/atm/jcb-prototype_lgetkf.yaml.j2"
  JCB_ALGO_YAML_OBS: "${PARMgfs}/gdas/atm/jcb-prototype_lgetkf_observer.yaml.j2"
  JCB_ALGO_YAML_SOL: "${PARMgfs}/gdas/atm/jcb-prototype_lgetkf_solver.yaml.j2"
  JCB_ALGO_YAML_FV3INC: "${PARMgfs}/gdas/atm/jcb-prototype_lgetkf-fv3inc.yaml.j2"
  LAYOUT_X_ATMENSANL: 8
  LAYOUT_Y_ATMENSANL: 8
  IO_LAYOUT_X: 1
  IO_LAYOUT_Y: 1

aeroanl:
  IO_LAYOUT_X: 1
  IO_LAYOUT_Y: 1

snowanl:
  IO_LAYOUT_X: 1
  IO_LAYOUT_Y: 1

marineanl:
  SOCA_INPUT_FIX_DIR: "${FIXgfs}/gdas/soca/72x35x25/soca"
  SOCA_OBS_LIST: "${PARMgfs}/gdas/soca/obs/obs_list.yaml"  # TODO: This is also repeated in oceanprepobs
  SOCA_NINNER: 100
  JCB_ALGO_YAML_VAR: "${PARMgfs}/gdas/soca/marine-jcb-3dfgat.yaml.j2"

prepoceanobs:
  SOCA_INPUT_FIX_DIR: "${FIXgfs}/gdas/soca/72x35x25/soca"
  SOCA_OBS_LIST: "${PARMgfs}/gdas/soca/obs/obs_list.yaml"  # TODO: This is also repeated in ocnanal
  OBSPREP_YAML: "${PARMgfs}/gdas/soca/obsprep/obsprep_config.yaml"
  use_exp_obs: "YES"
  dmpdir_exp: "${BASE_DATA}/experimental_obs"

# config.aero has just a system-specific path to add.
# This is handled by the setup_expt.py, but it has to be told to write to it.
aero: {}
