base:
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  KEEPDATA: "NO"
  DO_EXTRACTVARS: "NO"
  FHMAX_GFS: 120
  FHMAX_HF_GFS: 0
  FHOUT_HF_GFS: 1
  FCST_BREAKPOINTS: "48"
  REPLAY_ICS: "NO"
  FHOUT_GFS: 6
  FHOUT_OCN_GFS: 6
  FHOUT_ICE_GFS: 6
  HPSSARCH: "NO"
  LOCALARCH: "NO"
  SFS_POST: "NO"
  USE_OCN_ENS_PERTURB_FILES: "NO"
  USE_ATM_ENS_PERTURB_FILES: "NO"
  DO_TEST_MODE: "NO"
fcst:
  reforecast: "NO"
  FHZER: 6
  TYPE: "nh"
  MONO: "non-mono"
ocn:
  MOM6_INTERP_ICS: "NO"
# config.aero has just a system-specific path to add.
# This is handled by the setup_expt.py, but it has to be told to write to it.
aero: {}
